import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Navigation } from '@/src/components/navigation'
import { Provider } from '@/src/components/urql-provider/urql-provider'
import { Toaster } from '@/src/components/ui/toaster'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <Provider>
              <div className="h-screen w-full">
                <Navigation />
                {children}
              </div>
          </Provider>
          <Toaster />
        </main>
      </body>
    </html>
  )
}
